# -*- coding: utf-8 -*-
"""TrabalhoFinal1B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbzpzD1W82a6Y2Z7TX3rlDrAq6HWN4Lc
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
dataset = pd.read_csv("./datasets/student_mental_health_burnout.csv")

dataset.shape

dataset.isnull().sum()

dataset=dataset.drop('student_id',axis=1)

dataset.head(10)

dataset['burnout_level'].value_counts()

labelencoder = LabelEncoder()
dataset['year'] = labelencoder.fit_transform(dataset['year'])
dataset['stress_level'] = labelencoder.fit_transform(dataset['stress_level'])
dataset['sleep_quality'] = labelencoder.fit_transform(dataset['sleep_quality'])
dataset['internet_quality'] = labelencoder.fit_transform(dataset['internet_quality'])
dataset['burnout_level'] = labelencoder.fit_transform(dataset['burnout_level'])

dataset.head(10)

dataset['course'].value_counts()

dataset.shape

""" pd.get_dummies(dataset, columns=['gender']):

 É One hot Encoding automatico junto com label encoder.Essa função faz de  forma mais moderna e evita erros. Ela pega a coluna exemplo: ['gender'] cria as colunas:<br>
gender_Female,	gender_Male,	gender_Other<br>
0 0 1<br>
1 0 0
"""

#One hot Encoding automatico junto com label encoder: É uma forma mais moderna de fazer e evita erros ela pega a coluna exemplo gender cria as colunas gender_Female	gender_Male	gender_Other
dataset = pd.get_dummies(dataset, columns=['gender'])# mais 3 colunas
dataset = pd.get_dummies(dataset, columns=['course'])# mais 5 colunas

dataset.shape

dataset.head(10)
